const TECH_ICONS: Record<string, string> = {
  Angular: 'bi-triangle',
  React: 'bi-atom',
  'Vue.js': 'bi-lightning',
  TypeScript: 'bi-braces',
  JavaScript: 'bi-braces',
  HTML5: 'bi-filetype-html',
  CSS3: 'bi-filetype-css',
  'Next.js': 'bi-arrow-repeat',
  'Node.js': 'bi-server',
  Python: 'bi-filetype-py',
  Django: 'bi-diagram-3',
  Laravel: 'bi-boxes',
  NestJS: 'bi-hexagon',
  FastAPI: 'bi-lightning',
  PostgreSQL: 'bi-database',
  MySQL: 'bi-database-fill',
  MongoDB: 'bi-database-down',
  Firebase: 'bi-fire',
  Redis: 'bi-database-gear',
  Flutter: 'bi-phone',
  'React Native': 'bi-phone-landscape',
  Dart: 'bi-lightning-charge',
  Bootstrap: 'bi-bootstrap',
  'Tailwind CSS': 'bi-wind',
  'Material Design': 'bi-palette',
  Docker: 'bi-box-seam',
  Kubernetes: 'bi-diagram-3',
  AWS: 'bi-cloud',
  Stripe: 'bi-credit-card',
  'Chart.js': 'bi-bar-chart',
  'D3.js': 'bi-graph-up',
  'TensorFlow Lite': 'bi-cpu',
  Provider: 'bi-arrow-repeat',
  Redux: 'bi-arrow-clockwise',
  Celery: 'bi-gear',
  Bedrock: 'bi-robot',
  Lambda: 'bi-lightning-charge',
  Terraform: 'bi-bricks',
};

export function getTechIcon(tech: string): string {
  return TECH_ICONS[tech] || 'bi-code-slash';
}
